cloudformation:
  parameters:
    IPLISTCONFIGBUCKET: "iplist_bucket"
    IPLISTCONFIGPATH: "iplist_config/config.json"
    PYTHONUNBUFFERED: "1"
    HOSTPORT: "5000"
    CLUSTERNAME: "MyECSCluster"
    IMAGENAME: "repo/aws-ip-list-service:master-12"
    CONTAINERNAME: "aws-ip-list-service-container"
    DNSPREFIX: "ip-list"
    DNSZONE: "somewhere.com"
    TASKDESIREDCOUNT: "2"
    SERVICEROLE: "ecsServiceRole"
    CONTAINERPORT: "5000"
    LBSSLCERT: "arn:aws:iam:etc"
    REQUIREDCPU: "64"
    REQUIREDMEMORY: "128"
  stack_name: "aws-ip-list-service-stack"
  region: "us-east-1"
  cfn_template: "cfn-template.json"
  cpuLimit: "80"
  memoryLimit: "80"